pub const K: u32 = b'K' as u32;
pub const KSU_INSTALL_MAGIC1: u32 = 0xDEAD_BEEF;
pub const KSU_INSTALL_MAGIC2: u32 = 0xCAFE_BABE;
#[cfg(target_env = "gnu")]
pub const KSU_IOCTL_NUKE_EXT4_SYSFS: u64 = libc::_IOW::<()>(K, 17);
#[cfg(not(target_env = "gnu"))]
pub const KSU_IOCTL_NUKE_EXT4_SYSFS: i32 = libc::_IOW::<()>(K, 17);
#[cfg(target_env = "gnu")]
pub const KSU_IOCTL_GET_INFO: u64 = libc::_IOR::<()>(K, 2);
#[cfg(not(target_env = "gnu"))]
pub const KSU_IOCTL_GET_INFO: i32 = libc::_IOR::<()>(K, 2);
#[cfg(target_env = "gnu")]
pub const KSU_IOCTL_ADD_TRY_UMOUNT: u64 = libc::_IOW::<()>(K, 18);
#[cfg(not(target_env = "gnu"))]
pub const KSU_IOCTL_ADD_TRY_UMOUNT: i32 = libc::_IOW::<()>(K, 18);
